### ISSUE TITLE
Punctuation isn't consistent in Settings.cpp params

### ISSUE THREAD

**Issue by maxvonhippel** [argiopetech/base#65]
```
    cerr << "\t--startinglogAge" << endl;
    cerr << "\t--priorlogAge" << endl;
    cerr << "\t--sigmaLogAge" << endl;
```

The punctuation changes between ...logAge and ...LogAge.

Other such inconsistencies likely exist elsewhere in the list.  At some point it would be worth finding them all and fixing them to be consistent and predictable.

**Comment by maxvonhippel** [comment]
Also the names of the params read do not = those printed in the help message.  For example, the code looks for priorCarbonicity, but tells the user to use startingCarbonicity.

`{"priorCarbonicity", required_argument, 0, 0xCD},`

**Comment by tedvh** [comment]
good find!

**Comment by argiopetech** [comment]
Good call on the punctuation. That should be consistent. My guess is that the flags are consistent but the help text isn't, but I don't have the code in front of me at the moment.
