### ISSUE TITLE
base GitHub project name sub-optimal

### ISSUE THREAD

**Issue by maxvonhippel** [argiopetech/base#68]
This is an extremely low-priority issue, but I recently noticed that the repository name for this project is sub-optimal for its discovery.  If you search 'base' in GitHub, filter out only repositories, and set the language to C++, [there are still almost 21,000 results](https://github.com/search?l=C%2B%2B&q=base&type=Repositories&utf8=✓).

Could the repository be renamed base9?  This would put it with [only 4 other search results](https://github.com/search?l=C%2B%2B&q=base9&type=Repositories&utf8=✓), rather than 20k+.

@tedvh , thoughts?

**Comment by tedvh** [comment]
Thanks Max.  I'd be fine with that.  The issue is that we intend to eventually 
have a BASE-N and stop counting the number of parameter types (which is where 
the 9 comes from).  But we haven't even started the development to move BASE-9 
to BASE-N.

**Comment by maxvonhippel** [comment]
Maybe an alternative would be `BASE: Bayesian Analysis for Stellar Evolution' ?  That way users could add "stellar evolution" to their search and find it?

**Comment by tedvh** [comment]
I'm very happy with that.

**Comment by argiopetech** [comment]
If we did want to switch, I'd suggest astro-base. Otherwise, unpacking the acronym is the only result on github and the highlighted result on Google.

**Comment by maxvonhippel** [comment]
@argiopetech considering the fact that the acronym unpacked yields the right result I think it's fine to leave it as is.  But I'm fine with either.

Maybe a good thing to think about closer to the next publication, when search traffic will likely increase for the repository.

**Comment by tedvh** [comment]
Hmm, I'm game for either approach.  Don't know which would be better.

**Comment by argiopetech** [comment]
Our current URL is published in a number of documents. I suggest we stick with the current name for now.

**Comment by tedvh** [comment]
sounds reasonable.
