### ISSUE TITLE
failed in installing on MacOS 10.13.5

### ISSUE THREAD

**Issue by zouhu** [argiopetech/base#70]
Hus-MacBook-Pro:base zouhu$ ./build_local.sh
cp: yaml-cpp/CMakeLists.txt: Permission denied
-- The CXX compiler identification is AppleClang 9.1.0.9020039
-- The C compiler identification is AppleClang 9.1.0.9020039
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Looking for include file math.h
-- Looking for include file math.h - found
-- Looking for 7 include files gsl/gsl_blas.h, ..., gsl/gsl_errno.h
-- Looking for 7 include files gsl/gsl_blas.h, ..., gsl/gsl_errno.h - found
-- Looking for include file getopt.h
-- Looking for include file getopt.h - found
-- Looking for include file unistd.h
-- Looking for include file unistd.h - found
-- Looking for exp
-- Looking for exp - found
-- Looking for exp10
-- Looking for exp10 - not found
-- Looking for log
-- Looking for log - found
-- Looking for log10
-- Looking for log10 - found
-- Looking for pow
-- Looking for pow - found
-- Boost version: 1.67.0
-- Configuring done
-- Generating done
-- Build files have been written to: /Volumes/work/Palomar5/code/base/BUILD
Scanning dependencies of target base9
Scanning dependencies of target yaml-cpp
[  1%] Building CXX object yaml-cpp/CMakeFiles/yaml-cpp.dir/src/binary.cpp.o
[  4%] Building CXX object yaml-cpp/CMakeFiles/yaml-cpp.dir/src/directives.cpp.o
[  4%] Building CXX object yaml-cpp/CMakeFiles/yaml-cpp.dir/src/convert.cpp.o
[  5%] Building CXX object base9/CMakeFiles/base9.dir/Cluster.cpp.o
[  6%] Building CXX object yaml-cpp/CMakeFiles/yaml-cpp.dir/src/emit.cpp.o
[  8%] Building CXX object base9/CMakeFiles/base9.dir/Filters.cpp.o
In file included from /Volumes/work/Palomar5/code/base/yaml-cpp/src/convert.cpp:1:
In file included from /Volumes/work/Palomar5/code/base/yaml-cpp/include/yaml-cpp/node/convert.h:11:
In file included from /Volumes/work/Palomar5/code/base/yaml-cpp/include/yaml-cpp/node/iterator.h:12:
/Volumes/work/Palomar5/code/base/yaml-cpp/include/yaml-cpp/node/detail/iterator.h:47:55: error:
      no member named 'next' in namespace 'boost'
  ...void increment() { this->base_reference() = boost::next(this->base()); }
                                                 ~~~~~~~^
In file included from /Volumes/work/Palomar5/code/base/base9/Cluster.cpp:3:
In file included from /Volumes/work/Palomar5/code/base/base9/Cluster.hpp:7:
In file included from /Volumes/work/Palomar5/code/base/base9/Model.hpp:10:
In file included from /Volumes/work/Palomar5/code/base/base9/Settings.hpp:9:
In file included from /Volumes/work/Palomar5/code/base/yaml-cpp/include/yaml-cpp/yaml.h:14:
In file included from /Volumes/work/Palomar5/code/base/yaml-cpp/include/yaml-cpp/node/impl.h:10:
In file included from /Volumes/work/Palomar5/code/base/yaml-cpp/include/yaml-cpp/node/iterator.h:12:
/Volumes/work/Palomar5/code/base/yaml-cpp/include/yaml-cpp/node/detail/iterator.h:47:55: error:
      no member named 'next' in namespace 'boost'
  ...void increment() { this->base_reference() = boost::next(this->base()); }
                                                 ~~~~~~~^
1 error generated.
make[2]: *** [yaml-cpp/CMakeFiles/yaml-cpp.dir/src/convert.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
[  9%] Building CXX object base9/CMakeFiles/base9.dir/Model.cpp.o
make[1]: *** [yaml-cpp/CMakeFiles/yaml-cpp.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 10%] Building CXX object base9/CMakeFiles/base9.dir/Settings.cpp.o
1 error generated.
make[2]: *** [base9/CMakeFiles/base9.dir/Cluster.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
In file included from /Volumes/work/Palomar5/code/base/base9/Model.cpp:7:
In file included from /Volumes/work/Palomar5/code/base/base9/Model.hpp:10:
In file included from /Volumes/work/Palomar5/code/base/base9/Settings.hpp:9:
In file included from /Volumes/work/Palomar5/code/base/yaml-cpp/include/yaml-cpp/yaml.h:14:
In file included from /Volumes/work/Palomar5/code/base/yaml-cpp/include/yaml-cpp/node/impl.h:10:
In file included from /Volumes/work/Palomar5/code/base/yaml-cpp/include/yaml-cpp/node/iterator.h:12:
/Volumes/work/Palomar5/code/base/yaml-cpp/include/yaml-cpp/node/detail/iterator.h:47:55: error:
      no member named 'next' in namespace 'boost'
  ...void increment() { this->base_reference() = boost::next(this->base()); }
                                                 ~~~~~~~^
In file included from /Volumes/work/Palomar5/code/base/base9/Settings.cpp:11:
In file included from /Volumes/work/Palomar5/code/base/yaml-cpp/include/yaml-cpp/yaml.h:14:
In file included from /Volumes/work/Palomar5/code/base/yaml-cpp/include/yaml-cpp/node/impl.h:10:
In file included from /Volumes/work/Palomar5/code/base/yaml-cpp/include/yaml-cpp/node/iterator.h:12:
/Volumes/work/Palomar5/code/base/yaml-cpp/include/yaml-cpp/node/detail/iterator.h:47:55: error:
      no member named 'next' in namespace 'boost'
  ...void increment() { this->base_reference() = boost::next(this->base()); }
                                                 ~~~~~~~^
1 error generated.
make[2]: *** [base9/CMakeFiles/base9.dir/Model.cpp.o] Error 1
1 error generated.
make[2]: *** [base9/CMakeFiles/base9.dir/Settings.cpp.o] Error 1
make[1]: *** [base9/CMakeFiles/base9.dir/all] Error 2
make: *** [all] Error 2

**Comment by argiopetech** [comment]
Good day, Hu Zou,
Thank you for opening this issue. We're currently aware that this is a problem, and it is fixed in the [`develop`](/argiopetech/base/tree/develop) branch as of 25b166b14e386c9a99220725672aa9701929152b. Would you mind trying to build from that branch?

We're working hard to merge the development version into master soon. There are a few things left in the pipeline, so working directly from the development branch is probably the best bet for the next little while.

Thanks!
