### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by mkounkel** [argiopetech/base#71]
Trying to install this, running into a number of issues. 

Downloading 9.4.5.2, running the build.sh, it keeps complaining that there is no CMakeLists.txt in the base9 folder. 
Downloading the developer version, it keeps trying to clone https://github.com/argiopetech/yaml-cpp.git and is unable to find it, though, it is fixable by cloning it from a proper source in advance.

I was able to build it in the end on one machine after some trial and error (macbook pro, 2015), but another one, running the same OS (10.12.6) but newer hardware (imac, 2017), trying to make it with gcc results in an endless string of messages 
/var/tmp//ccxDhvFt.s:14950:no such instruction: `vmovsd %xmm0, 648(%rbp)'
/var/tmp//ccxDhvFt.s:14967:no such instruction: `vmovsd %xmm0, 656(%rbp)'
/var/tmp//ccxDhvFt.s:15517:no such instruction: `vzeroupper'
/var/tmp//ccxDhvFt.s:15600:no such instruction: `vzeroupper'
/var/tmp//ccxDhvFt.s:15735:no such instruction: `vzeroupper'

Tried using different gcc versions from 4.8 to 7.0 (installed via macports), all produce the same errors. I can build it using clang, but when trying to run singlePopMcmc using that build it keeps resulting in a segmentation error

**Comment by argiopetech** [comment]
9.5 (currently `develop`) is set to release shortly with a fixed build.sh. It's the recommended branch for now. 

Some cursory searching suggests GCC on Mac doesn't support AVX instructions. The recommended compiler on Mac OS X is the official clang.

singlePopMcmc should not segfault. The models have been in flux recently, so my guess is you're running an old/broken version of the models. The newest version is here: [https://github.com/argiopetech/base-models/archive/new_models.zip](https://github.com/argiopetech/base-models/archive/new_models.zip). There was an update in the last 3 weeks that may fix your issue. Don't forget to unpack PARSEC.model.bz2 and dsed_new.model.bz2

If the new models don't fix your issue, please feel to submit a new ticket detailing your problem with singlePopMcmc. Please include (e.g., in a gist) your base9.yaml, the actual commandline, and any output error messages. Compiling with debug_build.sh (or using cmake/ccmake to change your CMAKE_BUILD_TYPE to RELWITHDEBINFO) may yield more informative results. 

Thanks for your issue report! Feel free to reach out to me in email if you need non-issue support.
