### ISSUE TITLE
Gaia filters in simCluster

### ISSUE THREAD

**Issue by olivares-j** [argiopetech/base#72]
Hello,
First of all thanks for the grate code you have created.

So I just installed BASE-9  from the repository and run test with the default parameters from the base9.yml file and it worked well. Then I tried to do the same but using PARSEC model but when I run simCluster it only generates ugrizJHK photometry but it did not generate the G, G_BP and G_RP filters.  How can I get them? Thanks in advance.

**Comment by tedvh** [comment]
Hi Javier -

I just tried this and agree.  I got the same result.  I took a quick look at the
code and cannot find where we are ignoring the Gaia photometry columns.  I'm
looping Elliot Robinson, the group's software engineer, in on this.  If it is a
quick fix he may be able to help on a short timescale.

-Ted

**Comment by KevinBeeson** [comment]
Hi,

Thanks also for the code you have created. I just ran the code and encountered the same error. I was wondering if this is still an issue you are working on/found a fix?

Many thanks,

Kevin

**Comment by argiopetech** [comment]
It would appear this is an expected result of the white dwarf atmosphere models (Bergeron ~2013) not containing the filters you're looking for.

You can fix this either by running without white dwarfs (`--noWDs` flag), which will ignore the missing white dwarf filters and give you all available MS filters, or ensure you're on the newest code from the `master` branch and have the newest models so you can use the Bergeron 2019 atmospheres, which contain these filters.

Apologies for my long delay here. This issue somehow fell off my radar till Ted brought it back up to me last week.
