### ISSUE TITLE
Found unsupported star in photometry, type '9'... Continuing anyway.

### ISSUE THREAD

**Issue by sivdur** [argiopetech/base#73]
My input photometry file includes ID, J, H, K, sigJ, sigH, sigK columns of the 2MASS data and I use both old DSED and PARCES models but singlePopMcmc script gives me "Found unsupported star in photometry, type '9'... Continuing anyway." error. How should I give the input photometry file?

**Comment by tedvh** [comment]
type '9' refers to a neutron star or black hole.  This star will just be dropped from the fitting.
Did you generate the photometry file with simCluster or create it yourself?  If you are creating the photometry list then you want the star to be a type '1' if it is a MS or RGB star and type '3' if it is a WD.
If this provides insufficient information, post a few lines of your photometry file and I'll try to be more specific.

**Comment by sivdur** [comment]
I created the file containing the 2MASS data taken from the Vizier database. It is the data of a known open cluster. But I don't know what type the stars are. Shouldn't singlePopMcmc decide the star types?

a part of my input photometry file as follows:

id | J | H | K | sigJ | sigH | sigK
-- | -- | -- | -- | -- | -- | --
1 | 14.980 | 14.268 | 14.031 | 0.044 | 0.044 | 0.057
2 | 10.485 | 10.437 | 10.419 | 0.022 | 0.023 | 0.021
3 | 13.242 | 12.787 | 12.727 | 0.026 | 0.022 | 0.034
4 | 13.474 | 12.982 | 12.826 | 0.036 | 0.039 | 0.040
5 | 14.331 | 13.656 | 13.468 | 0.030 | 0.022 | 0.045
6 | 12.700 | 12.324 | 12.253 | 0.022 | 0.023 | 0.024
7 | 12.913 | 12.585 | 12.480 | 0.023 | 0.029 | 0.023
8 | 13.500 | 12.982 | 12.934 | 0.029 | 0.029 | 0.029
9 | 13.002 | 12.612 | 12.527 | 0.024 | 0.023 | 0.021
10 | 10.894 | 10.804 | 10.746 | 0.026 | 0.022 | 0.019
11 | 15.307 | 14.784 | 14.686 | 0.050 | 0.063 | 0.113
12 | 14.780 | 14.108 | 13.942 | 0.037 | 0.052 | 0.053
13 | 14.973 | 14.343 | 14.241 | 0.044 | 0.048 | 0.081

**Comment by tedvh** [comment]
You have a good point.  singlePopMcmc will work out the stellar types.  But it wasn't always so, and therefore the phot files have some legacy columns for backwards compatibility, as well as a few more columns that contain parameters that you will need.  Your file needs five more columns and should look something like this:
id    g      r      i      z      sigg  sigr  sigi  sigz  mass1 massRatio stage1 CMprior useDuringBurnIn
1955 10.866 10.471 10.336 10.273 0.010 0.010 0.010 0.010 1.5  0.0  1      1       1
1955 18.150 18.243 18.363 18.601 0.010 0.010 0.022 0.026 1.5  0.0  31      1       1

mass1 and massRatio are there for backward compatibility.  You can put any reasonable numbers there.
stage1 is the type of star.  If you don't know, just put '1' in, which will most likely be true (includes everything but a WD).
CMprior is needed and it is the prior probability that the object is a member of the cluster.  You can guess at this or be rigorous based on proper motions and/or RVs.
useDuringBurnin should be set to 1 unless you have a complicated cluster with a lot of background and aren't sure about the membership of most stars, in which case you'd set it to 0 for most stars and 1 for the stars that you think are highly likely to be cluster members.

**Comment by sivdur** [comment]
Thank you so much, It worked. Sorry for the late response, I waited for the simulation to be over. It took so much.

**Comment by tedvh** [comment]
Great.
